#!/usr/bin/env bash
#configure nginx server to listen for port 80
#this is spam
#this is spam
sudo sed -i 's/8080 default_sever/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
